spring.application.name=server

# server port
server.port=5959


# Database
# Database
spring.datasource.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.jdbc-url=jdbc:postgresql://localhost:5432/share
spring.datasource.hikari.username=postgres
spring.datasource.hikari.password=1234